export const GET_USER = 'get_user'
export const GET_AUTH = 'get_auth'
export const LOGOUT = 'logout'
export const CREATE_USER = 'create_user'
export const GET_USERS = 'get_users'
export const UPDATE_USER = 'update_user'
export const DELETE_USER = 'delete_user'
